FILENM 	=	'fig40'	;	%	
FIGCAP 	=	'Bedforms with spurs angle of climb nearly vertical' 	;	%	  (2)  Caption (CHARACTER VARIABLE)
SPCNGF 	=	30.0	;	%	(3)  WAVELENGTH OF BEDFORMS IN FIRST SET
PHASEF 	=	0.0	;	%	(4)  Bedform phase (controls placement within block diagram)
SMTRYF 	=	.1	;	%	(5)  Mean asymmetry
SMCHGF 	=	0.0	;	%	(6)  Amplitude of asymmetry cycle
SMPRDF 	=	1.0	;	%	(7)  Period of asymmetry cycle
SMFAZF 	=	0.0	;	%	(8)  Phase of asymmetry cycle
HTRTOF 	=	1.0 	;	%	  (9)  Mean steepness
HTCHGF 	=	0.0	;	%	(10) Amplitude of steepness cycle
HTPRDF 	=	1.0	;	%	(11) Period of steepness cycle
HTFAZF 	=	0.0	;	%	(12) Phase of steepness cycle
SNSPF1 	=	0.0	;	%	(13) Wavelength (along-crest) of first set of plan-form sinuosities
SNMGF1 	=	0.0	;	%	(14) Amplitude (measured in plan-form) of first set of sinuosities
SNFZF1 	=	0.0	;	%	(15) Phase of first set of sinuosities
SNVLF1 	=	0.0	;	%	(16) Migration speed (along-crest) of first set of sinuosities 
SNSPF2 	=	0.0	;	%	(17) Wavelength (along-crest) of second set of plan-form sinuosities
SNMGF2 	=	0.0	;	%	(18) Amplitude (measured in plan-form) of second set of sinuosities
SNFZF2 	=	0.0	;	%	(19) Phase of second set of sinuosities
SNVLF2 	=	0.0	;	%	(20) Migration speed (along-crest) of second set of sinuosities 
TRENDF 	=	90.0	;	%	(21) Migration direction of bedform
VELOCF 	=	.3	;	%	(22) Mean migration speed of bedform
VLCHGF 	=	0.0	;	%	(23) Amplitude of speed cycle
VLPRDF 	=	1.0	;	%	(24) Period of speed cycle
VLFAZF 	=	0.0	;	%	(25) Phase of speed cycle
SPCNGS 	=	30.0	;	%	(26) WAVELENGTH OF BEDFORMS IN SECOND SET
PHASES 	=	0.0	;	%	(27) Bedform phase (controls placement within block diagram)
SMTRYS 	=	0.0	;	%	(28) Mean asymmetry 
SMCHGS 	=	0.0	;	%	(29) Amplitude of asymmetry cycle
SMPRDS 	=	1.0	;	%	(30) Period of asymmetry cycle
SMFAZS 	=	0.0	;	%	(31) Phase of asymmetry cycle
HTRTOS 	=	1.0	;	%	 (32) Mean steepness
HTCHGS 	=	0.0	;	%	(33) Amplitude of steepness cycle
HTPRDS 	=	1.0	;	%	(34) Period of steepness cycle
HTFAZS 	=	0.0	;	%	(35) Phase of steepness cycle
SNSPS1 	=	0.0	;	%	(36) Wavelength (along-crest) of first set of plan-form sinuosities
SNMGS1 	=	0.0	;	%	(37) Amplitude (measured in plan-form) of first set of sinuosities
SNFZS1 	=	0.0	;	%	(38) Phase of first set of sinuosities
SNVLS1 	=	0.0	;	%	(39) Migration speed (along-crest) of first set of sinuosities 
SNSPS2 	=	0.0	;	%	(40) Wavelength (along-crest) of second set of plan-form sinuosities
SNMGS2 	=	0.0	;	%	(41) Amplitude (measured in plan-form) of second set of sinuosities
SNFZS2 	=	0.0	;	%	(42) Phase of second set of sinuosities
SNVLS2 	=	0.0	;	%	(43) Migration speed (along-crest) of second set of sinuosities 
TRENDS 	=	0.0	;	%	(44) Migration direction of bedform
VELOCS 	=	0.0	;	%	(45) Mean migration speed of bedform
VLCHGS 	=	0.0	;	%	(46) Amplitude of speed cycle
VLPRDS 	=	1.0	;	%	(47) Period of speed cycle
VLFAZS 	=	0.0	;	%	(48) Phase of speed cycle
SPCNGT 	=	0.0	;	%	(49) WAVELENGTH OF BEDFORMS IN THIRD SET
PHASET 	=	0.0	;	%	(50) Bedform phase (controls placement within block diagram)
SMTRYT 	=	0.0	;	%	(51) Mean asymmetry 
SMCHGT 	=	0.0	;	%	(52) Amplitude of asymmetry cycle
SMPRDT 	=	1.0	;	%	(53) Period of asymmetry cycle
SMFAZT 	=	0.0	;	%	(54) Phase of asymmetry cycle
HTRTOT 	=	0.0	;	%	(55) Mean steepness
HTCHGT 	=	0.0	;	%	(56) Amplitude of steepness cycle
HTPRDT 	=	1.0	;	%	(57) Period of steepness cycle
HTFAZT 	=	0.0	;	%	(58) Phase of steepness cycle
SNSPT1 	=	0.0	;	%	(59) Wavelength (along-crest) of first set of plan-form sinuosities
SNMGT1 	=	0.0	;	%	(60) Amplitude (measured in plan-form) of first set of sinuosities
SNFZT1 	=	0.0	;	%	(61) Phase of first set of sinuosities
SNVLT1 	=	0.0	;	%	(62) Migration speed (along-crest) of first set of sinuosities 
SNSPT2 	=	0.0	;	%	(63) Wavelength (along-crest) of second set of plan-form sinuosities
SNMGT2 	=	0.0	;	%	(64) Amplitude (measured in plan-form) of second set of sinuosities
SNFZT2 	=	0.0	;	%	(65) Phase of second set of sinuosities
SNVLT2 	=	0.0	;	%	(66) Migration speed (along-crest) of second set of sinuosities 
TRENDT 	=	0.0	;	%	(67) Migration direction of bedform
VELOCT 	=	0.0	;	%	(68) Mean migration speed of bedform
VLCHGT 	=	0.0	;	%	(69) Amplitude of speed cycle
VLPRDT 	=	1.0	;	%	(70) Period of speed cycle
VLFAZT 	=	0.0	;	%	(71) Phase of speed cycle
TYPE 	=	2	;	%	(72) Type of superpositioning (INTEGER)
CHOICE 	=	0	;	%	(73) Rotation option (INTEGER
ELVMIN 	=	-1.0	;	%	(74) Elevation of interdune flats 
DEPRAT 	=	.5	;	%	(75) Rate of deposition
DEPCHG 	=	0.0	;	%	(76) Amplitude of cycle in rate of deposition
DEPPRD 	=	1.0	;	%	(77) Period of cycle in rate of deposition
DEPFAZ 	=	0.0	;	%	(78) Phase of cycle in rate of deposition
NBEDSH 	=	2500	;	%	(79) Time from t=0 to beginning of depositional episode (INTEGER)
INTXBD 	=	4	;	%	(80) Interval between drawing of crossbeds (INTEGER)
FRMNUM 	=	10	;	%	(81) Time from t=0 to end of depositional episode (INTEGER)
CAPLOG 	=	'true'	;	%	(82) Print caption? (LOGICAL VARIABLE)
FILOG 	=	'true'	;	%	(83) Print name of input file? (LOGICAL VARIABLE)
FRMLOG 	=	'true'	;	%	(84) Print time at end of depositional episode? (LOGICAL VARIABLE)
IGRDSP 	=	1	;	%	(85) Precision? (low number) or speed? (high number); (1 2 4 5 or 10)
ZHORIZ 	=	1.0	;	%	(86) Elevation of horizontal section


